name: Package Cleanup

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "13 5 * * 0"

permissions:
  contents: read
  packages: write

jobs:
  package_cleanup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images: [nginx_good, nginx_bad, postfix_bad, mariadb_good, debian-weakkeys]
      max-parallel: 1

    steps:
      - name: Delete all untagged versions
        uses: snok/container-retention-policy@d3bdcf5ce9b05f685154e4a16c39233b245e3d53 # v3.1.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ matrix.images }}
          cut-off: "1h"
          tag-selection: untagged
          keep-n-most-recent: 0
