name: Package Cleanup

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "13 5 * * 0"

permissions:
  contents: read
  packages: write

jobs:
  package_cleanup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images: [nginx_good, nginx_bad, postfix_bad, mariadb_good, debian-weakkeys]

    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          owner: jsandas
          package-name: ${{ matrix.images }}
          package-type: container
          num-old-versions-to-delete: 1
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
